COUNTRIES = (
    ('', ('Select country')),
    ('Andorra', ('Andorra')),
    ('UAE', ('United Arab Emirates')),
    ('Afghanistan', ('Afghanistan')),
    ('Antigua & Barbuda', ('Antigua & Barbuda')),
    ('Anguilla', ('Anguilla')),
    ('Albania', ('Albania')),
    ('Armenia', ('Armenia')),
    ('Netherlands Antilles', ('Netherlands Antilles')),
    ('Angola', ('Angola')),
    ('Antarctica', ('Antarctica')),
    ('Argentina', ('Argentina')),
    ('American Samoa', ('American Samoa')),
    ('Ausria', ('Austria')),
    ('Australia', ('Australia')),
    ('Aruba', ('Aruba')),
    ('Azerbaijan', ('Azerbaijan')),
    ('Bosnia and Herzegovina', ('Bosnia and Herzegovina')),
    ('Barbados', ('Barbados')),
    ('Bangladesh', ('Bangladesh')),
    ('Belgium', ('Belgium')),
    ('Burkina Faso', ('Burkina Faso')),
    ('Bulgaria', ('Bulgaria')),
    ('Bahrain', ('Bahrain')),
    ('Burundi', ('Burundi')),
    ('Benin', ('Benin')),
    ('Bermuda', ('Bermuda')),
    ('BN', ('Brunei Darussalam')),
    ('Bolivia', ('Bolivia')),
    ('Brazil', ('Brazil')),
    ('Bahama', ('Bahama')),
    ('Bhutan', ('Bhutan')),
    ('Bouvet Island', ('Bouvet Island')),
    ('Botswana', ('Botswana')),
    ('Belarus', ('Belarus')),
    ('Belize', ('Belize')),
    ('Canada', ('Canada')),
    ('Cocos Islands', ('Cocos (Keeling) Islands')),
    ('Central African Republic', ('Central African Republic')),
    ('Congo', ('Congo')),
    ('Switzerland', ('Switzerland')),
    ('Ivory Coast', ('Ivory Coast')),
    ('Cook Islands', ('Cook Islands')),
    ('Chile', ('Chile')),
    ('Cameroon', ('Cameroon')),
    ('China', ('China')),
    ('Colombia', ('Colombia')),
    ('Costa Rica', ('Costa Rica')),
    ('Cuba', ('Cuba')),
    ('Cape Verde', ('Cape Verde')),
    ('CX', ('Christmas Island')),
    ('Cyprus', ('Cyprus')),
    ('CZ', ('Czech Republic')),
    ('Germany', ('Germany')),
    ('DJ', ('Djibouti')),
    ('Denmark', ('Denmark')),
    ('Dominica', ('Dominica')),
    ('Dominican Republic', ('Dominican Republic')),
    ('Algeria', ('Algeria')),
    ('Ecuador', ('Ecuador')),
    ('Estonia', ('Estonia')),
    ('Egypt', ('Egypt')),
    ('Western Sahara', ('Western Sahara')),
    ('Eritrea', ('Eritrea')),
    ('Spain', ('Spain')),
    ('Ethiopia', ('Ethiopia')),
    ('Finland', ('Finland')),
    ('Fiji', ('Fiji')),
    ('FK', ('Falkland Islands (Malvinas)')),
    ('FM', ('Micronesia')),
    ('FO', ('Faroe Islands')),
    ('France', ('France')),
    ('France, Metropolitan', ('France, Metropolitan')),
    ('Gabon', ('Gabon')),
    ('UK', ('United Kingdom (Great Britain)')),
    ('GD', ('Grenada')),
    ('Georgia', ('Georgia')),
    ('GF', ('French Guiana')),
    ('Ghana', ('Ghana')),
    ('GI', ('Gibraltar')),
    ('Greenland', ('Greenland')),
    ('Gambia', ('Gambia')),
    ('Guinea', ('Guinea')),
    ('GP', ('Guadeloupe')),
    ('GQ', ('Equatorial Guinea')),
    ('Greece', ('Greece')),
    ('GS', ('South Georgia and the South Sandwich Islands')),
    ('GT', ('Guatemala')),
    ('GU', ('Guam')),
    ('Guinea-Bissau', ('Guinea-Bissau')),
    ('Guyana', ('Guyana')),
    ('Hong Kong', ('Hong Kong')),
    ('Heard & McDonald Islands', ('Heard & McDonald Islands')),
    ('Honduras', ('Honduras')),
    ('Croatia', ('Croatia')),
    ('Haiti', ('Haiti')),
    ('Hungary', ('Hungary')),
    ('Indonesia', ('Indonesia')),
    ('Ireland', ('Ireland')),
    ('Israel', ('Israel')),
    ('India', ('India')),
    ('IO', ('British Indian Ocean Territory')),
    ('Iraq', ('Iraq')),
    ('IR', ('Islamic Republic of Iran')),
    ('Iceland', ('Iceland')),
    ('Italy', ('Italy')),
    ('Jamaica', ('Jamaica')),
    ('Jordan', ('Jordan')),
    ('Japan', ('Japan')),
    ('Kenya', ('Kenya')),
    ('KG', ('Kyrgyzstan')),
    ('Cambodia', ('Cambodia')),
    ('KI', ('Kiribati')),
    ('Comoros', ('Comoros')),
    ('KN', ('St. Kitts and Nevis')),
    ('KP', ('Korea, Democratic People\'s Republic of')),
    ('KR', ('Korea, Republic of')),
    ('Kuwait', ('Kuwait')),
    ('KY', ('Cayman Islands')),
    ('Kazakhstan', ('Kazakhstan')),
    ('LA', ('Lao People\'s Democratic Republic')),
    ('Lebanon', ('Lebanon')),
    ('Saint Lucia', ('Saint Lucia')),
    ('LI', ('Liechtenstein')),
    ('Sri Lanka', ('Sri Lanka')),
    ('Liberia', ('Liberia')),
    ('Lesotho', ('Lesotho')),
    ('LT', ('Lithuania')),
    ('Luxembourg', ('Luxembourg')),
    ('Latvia', ('Latvia')),
    ('LY', ('Libyan Arab Jamahiriya')),
    ('Morocco', ('Morocco')),
    ('Monaco', ('Monaco')),
    ('MD', ('Moldova, Republic of')),
    ('MG', ('Madagascar')),
    ('MH', ('Marshall Islands')),
    ('ML', ('Mali')),
    ('Mongolia', ('Mongolia')),
    ('MM', ('Myanmar')),
    ('Macau', ('Macau')),
    ('MP', ('Northern Mariana Islands')),
    ('MQ', ('Martinique')),
    ('Mauritania', ('Mauritania')),
    ('MS', ('Monserrat')),
    ('Malta', ('Malta')),
    ('Mauritius', ('Mauritius')),
    ('Maldives', ('Maldives')),
    ('Malawi', ('Malawi')),
    ('Mexico', ('Mexico')),
    ('Malaysia', ('Malaysia')),
    ('MZ', ('Mozambique')),
    ('NA', ('Namibia')),
    ('NC', ('New Caledonia')),
    ('Niger', ('Niger')),
    ('NF', ('Norfolk Island')),
    ('Nigeria', ('Nigeria')),
    ('NI', ('Nicaragua')),
    ('Netherlands', ('Netherlands')),
    ('Norway', ('Norway')),
    ('Nepal', ('Nepal')),
    ('NR', ('Nauru')),
    ('Niue', ('Niue')),
    ('New Zealand', ('New Zealand')),
    ('Oman', ('Oman')),
    ('Panama', ('Panama')),
    ('Peru', ('Peru')),
    ('French Polynesia', ('French Polynesia')),
    ('PG', ('Papua New Guinea')),
    ('Phillipines', ('Philippines')),
    ('Pakistan', ('Pakistan')),
    ('Poland', ('Poland')),
    ('PM', ('St. Pierre & Miquelon')),
    ('Pitcairn', ('Pitcairn')),
    ('Puerto Rico', ('Puerto Rico')),
    ('Portugal', ('Portugal')),
    ('Palau', ('Palau')),
    ('Paraguay', ('Paraguay')),
    ('Qatar', ('Qatar')),
    ('Reunion', ('Reunion')),
    ('Romania', ('Romania')),
    ('RUssia', ('Russian Federation')),
    ('Rwanda', ('Rwanda')),
    ('Saudi Arabia', ('Saudi Arabia')),
    ('Solomon Islands', ('Solomon Islands')),
    ('Seychelles', ('Seychelles')),
    ('Sudan', ('Sudan')),
    ('Sweden', ('Sweden')),
    ('Singapore', ('Singapore')),
    ('St. Helena', ('St. Helena')),
    ('Slovenia', ('Slovenia')),
    ('Svalbard', ('Svalbard & Jan Mayen Islands')),
    ('Slovokia', ('Slovakia')),
    ('Sirra Leone', ('Sierra Leone')),
    ('SM', ('San Marino')),
    ('Senegal', ('Senegal')),
    ('Somalia', ('Somalia')),
    ('Suriname', ('Suriname')),
    ('Sao Tome', ('Sao Tome & Principe')),
    ('El Salvador', ('El Salvador')),
    ('SY', ('Syrian Arab Republic')),
    ('Swaziland', ('Swaziland')),
    ('TC', ('Turks & Caicos Islands')),
    ('Chad', ('Chad')),
    ('TF', ('French Southern Territories')),
    ('Togo', ('Togo')),
    ('TH', ('Thailand')),
    ('TJ', ('Tajikistan')),
    ('TK', ('Tokelau')),
    ('TM', ('Turkmenistan')),
    ('Tunisia', ('Tunisia')),
    ('Tonga', ('Tonga')),
    ('East Timor', ('East Timor')),
    ('Turkey', ('Turkey')),
    ('Trinidad', ('Trinidad & Tobago')),
    ('Tuvalu', ('Tuvalu')),
    ('Taiwan, Province of China', ('Taiwan, Province of China')),
    ('Tanzania, United Republic of', ('Tanzania, United Republic of')),
    ('Ukraine', ('Ukraine')),
    ('Uganda', ('Uganda')),
    ('United States Minor', ('United States Minor Outlying Islands')),
    ('United States', ('United States of America')),
    ('Uruguay', ('Uruguay')),
    ('Uzbekistan', ('Uzbekistan')),
    ('Vatican City', ('Vatican City State (Holy See)')),
    ('VC', ('St. Vincent & the Grenadines')),
    ('Venezuela', ('Venezuela')),
    ('VG', ('British Virgin Islands')),
    ('VI', ('United States Virgin Islands')),
    ('Viet Nam', ('Viet Nam')),
    ('Vunauatu', ('Vanuatu')),
    ('WF', ('Wallis & Futuna Islands')),
    ('Samoa', ('Samoa')),
    ('Yemen', ('Yemen')),
    ('Mayotte', ('Mayotte')),
    ('Yugoslavia', ('Yugoslavia')),
    ('South Africa', ('South Africa')),
    ('Zambia', ('Zambia')),
    ('Zaire', ('Zaire')),
    ('Zimbabwe', ('Zimbabwe')),
    ('ZZ', ('Unknown or unspecified country')),
)
sorted_countries = sorted(COUNTRIES, key=lambda x: x[1])